### ISSUE TITLE
Unhandled exit code when vcredist is not installed.

### ISSUE THREAD

**Issue by shivammathur** [mlocati/powershell-phpmanager#104]
On GitHub Actions, I'm getting a different exit code when vcredist is not installed for x86 version of PHP. 

`0xC0000135` and `0xC0000139` are checked, but I'm getting `0xc000007b`.
https://github.com/mlocati/powershell-phpmanager/blob/8681006539108076d6263dc4998c56a1d9613ea0/PhpManager/private/Install-PhpFromUrl.ps1#L58

Logs: https://github.com/shivammathur/test-setup-php/actions/runs/3918173849/jobs/6698400981#step:3:1

**Comment by mlocati** [comment]
That `0xC000007B` error is named [`STATUS_INVALID_IMAGE_FORMAT`](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55): maybe because a 32 bit program is trying to use a 64 bit DLL?
BTW, what about #104 ?

**Comment by mlocati** [comment]
> BTW, what about #104 ?

Sorry, #105

**Comment by shivammathur** [comment]
Yes, that should fix it.

**Comment by shivammathur** [comment]
@mlocati Please tag a patch release.

**Comment by mlocati** [comment]
I'm not in front of a PC at the moment, but of course I'll do that asap

**Comment by mlocati** [comment]
> @mlocati Please tag a patch release.

Done.

**Comment by shivammathur** [comment]
Thanks for fixing this and the release.
