### ISSUE TITLE
ExtensionDetail from DLL Path causing error when using local file and not PECL

### ISSUE THREAD

**Issue by jmwamser** [mlocati/powershell-phpmanager#113]
Due to PECL not having DLLs for the `pdo_sqlsrv` and `sqlsrv` for PHP 8+, I am trying to use PhpManager to install the files I have downloaded from the [mssql](https://github.com/microsoft/msphpsql/releases) git repo. 

When I run `Install-PhpExtension -Path C:\PHP\82 C:\temp\php_sqlsrv_82_nts.dll` I receive this error: `The variable '$newExtension' cannot be retrieved because it has not been set.` 

Looking into the `Install-PhpExtension` script I found the following line that I believe is causing the issue.

https://github.com/mlocati/powershell-phpmanager/blob/a1e72320ddc178800bd781abc33e2917d7fdbbff/PhpManager/public/Install-PhpExtension.ps1#L229

I believe this is because the variable is only set in the else part of the if statement on line 212.
https://github.com/mlocati/powershell-phpmanager/blob/a1e72320ddc178800bd781abc33e2917d7fdbbff/PhpManager/public/Install-PhpExtension.ps1#L85-L228
https://github.com/mlocati/powershell-phpmanager/blob/a1e72320ddc178800bd781abc33e2917d7fdbbff/PhpManager/public/Install-PhpExtension.ps1#L212

I wonder if moving line 212 right after the closing if statement bracket on line 228 would fix this issue.

Thank you for your hard work on this! I'll see if I can get a pull request put together.

**Comment by mlocati** [comment]
Thanks for the report!

> `Install-PhpExtension -Path C:\PHP\82 C:\temp\php_sqlsrv_82_nts.dll`

Did you mean `Install-PhpExtension -Extension C:\PHP\82 C:\temp\php_sqlsrv_82_nts.dll`, right?

> I wonder if moving line 212 right after the closing if statement bracket on line 228 would fix this issue.

Nope, I think #114 is a better fix.

**Comment by jmwamser** [comment]
Thank you for the quick update. This fixed the issue I was experiencing.
