### ISSUE TITLE
extensions - simple listing

### ISSUE THREAD

**Issue by ltdeta** [mlocati/powershell-phpmanager#17]
the function ```Getting the list of PHP extensions```  shows a lot of detail information

Type         : Builtin
State        : Builtin
Name         : zlib
Handle       : zlib
Version      : 
PhpVersion   : 7.2.12
Architecture : x86
ThreadSafe   : True
Filename     : 

An additional way to get only the names in a simple list would be helpful

**Comment by mlocati** [comment]
What about this?

```PowerShell
Get-PhpExtension | Select-Object -Property Handle
```

**Comment by mlocati** [comment]
You can also do something very handy like

```PowerShell
Get-PhpExtension | Where-Object {$_.State -ne 'Disabled'} | Select-Object -Property Handle,Type
```

**Comment by ltdeta** [comment]
Thank you, that's exactly what I was looking for
