### ISSUE TITLE
Instruction Adding new extensions (from PECL)

### ISSUE THREAD

**Issue by ltdeta** [mlocati/powershell-phpmanager#18]
The instructions chapter "Adding new extensions (from PECL)" should be extended.
It is not clear that a path is mandatory.

> 
> PS D:\php7> Install-PhpExtension win32service
> No PHP versions found in the current PATHs: use the -Path argument to specify the location of installed PHP
> At C:\Program Files\WindowsPowerShell\Modules\PhpManager\1.13.0.176\private\PhpVersion.ps1:309 char:13
> +             throw "No PHP versions found in the current PATHs: use th ...
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (No PHP versions...f installed PHP:String) [], RuntimeException
>     + FullyQualifiedErrorId : No PHP versions found in the current PATHs: use the -Path argument to specify the location of installed PHP
>  
>

**Comment by mlocati** [comment]
The [README.md](https://github.com/mlocati/powershell-phpmanager/blob/master/README.md) file is meant to be give a generic introduction of all the available functions.

As stated [here](https://github.com/mlocati/powershell-phpmanager#available-features), to get detailed informations about a command you can run

```PowerShell
Get-Help -Detailed Install-PhpExtension
```

**Comment by ltdeta** [comment]
Ok
