### ISSUE TITLE
Set-Content : Stream was not readable

### ISSUE THREAD

**Issue by compuvin** [mlocati/powershell-phpmanager#21]
Randomly when trying to enable or disable a PHP Extension I get the following error message and the INI file is completely cleared(!):

![image](https://user-images.githubusercontent.com/619451/51129474-8ad42d00-17f8-11e9-9db4-dcabb2dcc59c.png)

Obviously the big thing is the clearing out of the file. I attempted to remedy it a few different ways but was unsuccessful. The cause, I'm guessing, is that IIS is checking for changes to the PHP.ini file in the FastCGI application and if I get it just at that moment, the error occurs.

**Comment by mlocati** [comment]
Did you close and reopen the powershell window after editing the file? (Otherwise powershell uses the previous version of the file, without the edits)

**Comment by compuvin** [comment]
Yes, I did close powershell and reopen it.

**Comment by mlocati** [comment]
What about [these other changes](https://github.com/mlocati/powershell-phpmanager/pull/23/files#diff-91dca379128b975487932c5cccb6e6a3)?

**Comment by compuvin** [comment]
Michele, that seems to have done it. I couldn't get it to break this time. Thanks for the fix.

**Comment by mlocati** [comment]
I just released a new version.
To update it, simply open a powershell prompt with admin rights and execute this command:

```PowerShell
Update-Module PhpManager -Force
```
