### ISSUE TITLE
Update-Php: specified version

### ISSUE THREAD

**Issue by ltdeta** [mlocati/powershell-phpmanager#25]
```update-php```
The command will automatically check if there's a newer version available: if so, the PHP installation will be upgraded. 

It would be nice if you could specify a version, and not necessarily update to the latest version.

**Comment by mlocati** [comment]
What about using `Install-Php` instead?

**Comment by ltdeta** [comment]
Is the existing configuration retained?

**Comment by mlocati** [comment]
Yes, if you don't specify the `InitialPhpIni` parameter

**Comment by ltdeta** [comment]
If you want, you can extend the description as follows.

### Updating PHP to a specified version
Use the ```Install-Php``` command to update PHP (for example existing version 7.2.10 to 7.2.15). 
If you don't specify the ```InitialPhpIni``` parameter all  settings are retained.
```
Install-Php -Version 7.2.15 -Architecture x64 -ThreadSafe 0 -Path C:\PHP
```

**Comment by mlocati** [comment]
What about editing the [README.md](https://github.com/mlocati/powershell-phpmanager/blob/master/README.md) file yourself? Just click that link, and click the pencil icon :wink:

**Comment by ltdeta** [comment]
done 😉
