### ISSUE TITLE
command for current php versions

### ISSUE THREAD

**Issue by ltdeta** [mlocati/powershell-phpmanager#27]
Is it possible to add a function to query the current stable php versions?

some examples 
```powershell
Versions-Php 7
```
result:   7.0.33 / 7.1.27 / 7.2.16 / 7.3.3

```powershell
Versions-Php 7.2*
```
result:   7.2.16

```powershell
Versions-Php 5.6*
```
result: 5.6.40

**Comment by mlocati** [comment]
You can use the `Get-PhpAvailableVersion` function. For example, to get the latest 7.2 version, you can use this line:

```PowerShell
Get-PhpAvailableVersion Release | Where-Object { $_.Version -match '^7\.2\.' } | Select-Object -Last 1 | Select-Object Version
```

**Comment by ltdeta** [comment]
ok, thanks
