### ISSUE TITLE
Unrecognized PHP extension name: ionCube Loader

### ISSUE THREAD

**Issue by joergweber** [mlocati/powershell-phpmanager#32]
I have a working PHP 7.2 installation that includes ionCube Loader (https://www.ioncube.com/loaders.php). I wanted to add my existing PHP installation to PhpSwitcher in order to install imagick, but I always get the error message `Unrecognized PHP extension name: ionCube Loader`

What I did:

```
Initialize-PhpSwitcher -Alias C:\PHP\CurrentVersion -Scope CurrentUser
Add-PhpToSwitcher -Name 7.2 -Path C:\XAMPP\PHP
Switch-Php 7.2 -force
Install-PhpExtension -Extension imagick -MinimumStability snapshot

Unrecognized PHP extension name: ionCube Loader
At C:\Program Files\WindowsPowerShell\Modules\PhpManager\1.15.0.191\private\Get-PhpExtensionHandle.ps1:37 char:21
+                     throw "Unrecognized PHP extension name: $Name"
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unrecognized PH... ionCube Loader:String) [], RuntimeException
    + FullyQualifiedErrorId : Unrecognized PHP extension name: ionCube Loader
```

I also added the LoadModule and PhpIniDir instructions to the http.conf. What am I doing wrong here?

**Comment by mlocati** [comment]
The problem is that ionCube Loader is not available in the PECL archives (https://windows.php.net/downloads/pecl/releases/ or https://windows.php.net/downloads/pecl/snaps/), so PhpManager can't find it (maybe I should add a note about that in the README file).

**Comment by joergweber** [comment]
I get that, and I was checking before that ionCube was not in PECL. But I am not planning to manage/install ionCube with PhpManager - it is already installed. I find it a bit puzzling that PhpManager complains about an extension that it is not supposed to touch - but perhaps I am misunderstanding what PhpManager does...

**Comment by mlocati** [comment]
Sorry, you are right of course: I didn't read carefully your error message.

I just released a new version to fix this issue. You can upgrade it in an elevated PowerShell with the following command:

```PowerShell
Update-Module -Name PhpManager
```

**Comment by joergweber** [comment]
Thanks, that worked now!

**Comment by mlocati** [comment]
@range-of-motion any reason for that :-1: ?

**Comment by range-of-motion** [comment]
Because it didn't work for me :P

**Comment by mlocati** [comment]
What exactly didn't work?

**Comment by range-of-motion** [comment]
.. the "fix" that was proposed by you? I can't remember the exact details anymore, it was for a coworker's PC. I don't touch Windows.

**Comment by mlocati** [comment]
Well, a bare :-1: doesn't give me enough details to understand what's going wrong 😉
