### ISSUE TITLE
Unable to install PHP extensions

### ISSUE THREAD

**Issue by kranack** [mlocati/powershell-phpmanager#37]
I'm experiencing an issue during the installation of any PHP extensions. I think it's related to the space in the path to my PHP directory because I can't reproduce this issue with a path like "C:/PHP".

Here is a screenshot of the error I get during the installation.

![image](https://user-images.githubusercontent.com/2787828/67187459-89204100-f3ea-11e9-9bd4-9dc07fa8c556.png)

The error says
"Move-Item: Impossible to find a part of the access path.
At character: ......"

**Comment by mlocati** [comment]
It seems it's working for me. Are you running an elevated powershell (that is, did you launch it as administrator)?
I'm asking because usually folders and files under `C:\Program Files` can be modified only by administrators

**Comment by mlocati** [comment]
Also, could you check which version of PhpManager you are using? You can check it by running

```PowerShell
Get-Module -Name PhpManager
```

If the above command returns an empty result, you can run

```PowerShell
Get-Module -Name PhpManager -ListAvailable
```

**Comment by mlocati** [comment]
I really don't understand what's going wrong. Everything seems ok to me... Maybe the MongoDB extension requires some DLL that's not installed in your system?

I just updated Phpmanager (with [this little change](https://github.com/mlocati/powershell-phpmanager/commit/7f02fbb61650ab273447fc809bc02cc2338947bd)). so that it's a bit more verbose when installing an extension.

Could you update the PhpManager powershell module, and retry to install the mongodb extension (with the `-Verbose` flag)?

**Comment by mlocati** [comment]
Here's my output:

```
PS C:\WINDOWS\system32> Install-Php -Version 7.3 -Architecture x64 -ThreadSafe $true -Path 'C:\Program Files\PHP' -TimeZone UTC -InitialPhpIni Production -Verbose
DETAILED: GET https://windows.php.net/downloads/releases/ with 0-byte payload
DETAILED: received 6821-byte response of content type text/html; charset=UTF-8
DETAILED: Installing PHP PHP 7.3.10 x64 (64-bit) Thread-Safe
DETAILED: Downloading from https://windows.php.net/downloads/releases/php-7.3.10-Win32-VC15-x64.zip
DETAILED: GET https://windows.php.net/downloads/releases/php-7.3.10-Win32-VC15-x64.zip with 0-byte payload
DETAILED: received 25716166-byte response of content type application/x-zip-compressed
DETAILED: Extracting C:\Dev\cache\php-7.3.10-Win32-VC15-x64.zip to temporary directory
DETAILED: Extracting C:\Dev\cache\php-7.3.10-Win32-VC15-x64.zip to destination directory

PS C:\WINDOWS\system32> Install-PhpExtension -Extension mongodb -Version 1.5 -Path 'C:\Program Files\PHP' -Verbose
DETAILED: GET https://pecl.php.net/rest/p/packages.xml with 0-byte payload
DETAILED: received 6550-byte response of content type application/xml
DETAILED: GET https://pecl.php.net/rest/r/mongodb/allreleases.xml with 0-byte payload
DETAILED: received 2779-byte response of content type application/xml
DETAILED: GET https://windows.php.net/downloads/pecl/releases/mongodb/1.5.5 with 0-byte payload
DETAILED: received 2375-byte response of content type text/html; charset=UTF-8
DETAILED: Downloading PECL package mongodb 1.5.5 from https://windows.php.net/downloads/pecl/releases/mongodb/1.5.5/php_mongodb-1.5.5-7.3-ts-vc15-x64.zip
DETAILED: Downloading from https://windows.php.net/downloads/pecl/releases/mongodb/1.5.5/php_mongodb-1.5.5-7.3-ts-vc15-x64.zip
DETAILED: GET https://windows.php.net/downloads/pecl/releases/mongodb/1.5.5/php_mongodb-1.5.5-7.3-ts-vc15-x64.zip with 0-byte payload
DETAILED: received 1331506-byte response of content type application/x-zip-compressed
DETAILED: Installing new extension 'mongodb' version 1.5.5
DETAILED: Checking prerequisites for mongodb
DETAILED: Moving "J:\Temp\5k1dtzxk.bmi\php_mongodb.dll" to "C:\Program Files\PHP\ext\php_mongodb.dll"
DETAILED: Enabling extension "mongodb" for "C:\Program Files\PHP\php.exe"
DETAILED: The extension mongodb v1.5.5 has been enabled
```

**Comment by kranack** [comment]
> Could you update the PhpManager powershell module, and retry to install the mongodb extension (with the `-Verbose` flag)?

Sure, here's my output
![image](https://user-images.githubusercontent.com/2787828/67217334-d4efdc00-f424-11e9-9395-77dc45889959.png)

It seems that's the module is ignoring my `-Path` parameter and trying to move the extension in `C:\PHP` directory.
I think the only difference with your test is I've installed my PHP binaries with `choco install php` ([Chocolatey](https://chocolatey.org/) package manager). Is your module compatible with any PHP installations or should I install my PHP with your module too ?

**Comment by mlocati** [comment]
Could you try to run this command?

```ps
Get-Php -Path 'C:\Program Files\PHP'
```

**Comment by kranack** [comment]
Well, I think I find my mistake here...

![image](https://user-images.githubusercontent.com/2787828/67218790-43ce3480-f427-11e9-8fd9-1a00e3977927.png)

I didn't know PHP will take `C:\PHP\ext` as default extension dir.... I changed the path in php.ini and it worked as expected :)

Thanks for your help and sorry for the inconvenience.

**Comment by mlocati** [comment]
Don't worry:wink:
Salut!!

**Comment by mlocati** [comment]
PS: I just released a new version that [includes a check about the extension dir](https://github.com/mlocati/powershell-phpmanager/commit/86a088cb7aba3ef0c307f89af2cc8328fe9a81eb).
