### ISSUE TITLE
Cannot switch PHP version due to missing drive

### ISSUE THREAD

**Issue by Remo** [mlocati/powershell-phpmanager#38]
I'm trying to switch the PHP version, but it fails becaues of a missing drive. I only have one drive (C:) on this computer. Any hint where I can look to fix this?

```ps
PS C:\WINDOWS\system32> Initialize-PhpSwitcher -Alias C:\PHP -Scope CurrentUser
PS C:\WINDOWS\system32> Add-PhpToSwitcher -Name 7.2 -Path C:\PHP72
PS C:\WINDOWS\system32> Add-PhpToSwitcher -Name 7.1 -Path C:\PHP71
PS C:\WINDOWS\system32> Get-PhpSwitcher

Scope       Alias  Targets    Current
-----       -----  -------    -------
CurrentUser C:\PHP {7.1, 7.2}


PS C:\WINDOWS\system32> Switch-Php 7.1
Join-Path : Cannot find drive. A drive with the name 'D' does not exist.
At C:\Program Files\WindowsPowerShell\Modules\PhpManager\1.17.2.210\private\PhpVersion.ps1:328 char:27
+                     $ep = Join-Path -Path $path -ChildPath 'php.exe'
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:String) [Join-Path], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
```

**Comment by mlocati** [comment]
`Switch-Php` checks the PHP installations available in the `PATH` environment variable (see [here](https://github.com/mlocati/powershell-phpmanager/blob/1.17.2/PhpManager/public/Switch-Php.ps1#L61)).
When that operation is performed, PhpManager inspects the found PHP installations (see [here](https://github.com/mlocati/powershell-phpmanager/blob/1.17.2/PhpManager/private/PhpVersion.ps1#L259)).
If one of those PHP installations is misconfigured, the process aborts.

Maybe is this your case? You can check it for example by running `Get-Php`

PS: Ciao Remo!!

**Comment by Remo** [comment]
Ciao Michele 😄 
yes, you're absolutely right! I removed that variable and it's now working fine.

**Comment by mlocati** [comment]
:+1:
