### ISSUE TITLE
Users rights on extensions

### ISSUE THREAD

**Issue by kranack** [mlocati/powershell-phpmanager#49]
**Environment**
Windows 2016 Server
PHP 7.3.x
PHPManager 1.20.0

**Issue Description**
When installing extensions with the PHPManager module, the rights applied on the files are not those I'm expecting. I installed PHP and ImageMagick with [Chocolatey](https://chocolatey.org/) and installed ssh2, mongodb and imagick PHP extensions with your module on my windows. Chocolatey seems to apply additionnal read/execute rights for standard users when PHPManager only add the current user rights (here, administrator).
Here's some screenshots to make it more comprehensible.

![image](https://user-images.githubusercontent.com/2787828/71623678-a2a9ea00-2bde-11ea-829c-407e07f37914.png)
There are the rights applied to sqlite3 extension, "Utilisateurs" refers to all "Users" on the machine I think.

![image](https://user-images.githubusercontent.com/2787828/71623697-bce3c800-2bde-11ea-9107-0445247111c6.png)
There are the rights applied to imagick extension, "J2S" is the user who installed the extension.

I've managed to copy rights with the Get-Acl and Set-Acl commands but I wonder if it could be possible to set these rights "in the Chocolatey way" instead of using the current user (I have no clue of how it's working for Windows).

**Comment by mlocati** [comment]
The brand new PHPManager version 1.22.1 should solve this issue.
