### ISSUE TITLE
Unable to enable extension under 7.4

### ISSUE THREAD

**Issue by ruudboon** [mlocati/powershell-phpmanager#52]
I'm trying to enable an extension under 7.4. It works with same config fine under 7.2 and 7.3. And under 7.4 it properly detects the extension but unfortunately it doesn't enable it.

https://github.com/ruudboon/cphalcon/runs/399772237#step:23:166

**Comment by mlocati** [comment]
At https://github.com/ruudboon/cphalcon/runs/399772237#step:23:166 we read that PHP is compiled without thread safety, at https://github.com/ruudboon/cphalcon/runs/399772237#step:23:166 we read that the extension is compiled with thread safety: they should match

**Comment by ruudboon** [comment]
Ahh thbx! Sorry for missing this

**Comment by mlocati** [comment]
Don't worry, four eyes is better than two
