### ISSUE TITLE
yaml extension fails to enable PHP < 7.2 as it need yaml.dll in path

### ISSUE THREAD

**Issue by shivammathur** [mlocati/powershell-phpmanager#55]
@mlocati To enable `yaml` extension PHP versions before 7.2 require `yaml.dll`. So currently it is required to manually extracting yaml.dll from the zip into a directory in windows path, it would be great if yaml.dll if found in the zip archive is extracted to the directory in `-Path` parameter or the default PHP directory.

**Comment by mlocati** [comment]
Fixed in #56. I'll release a new version as [tests complete](https://ci.appveyor.com/project/mlocati/powershell-phpmanager).
Thanks for reporting this issue.

**Comment by mlocati** [comment]
New version 1.22.5.306 [published](https://www.powershellgallery.com/packages/PhpManager/1.22.5.306).
