### ISSUE TITLE
couchbase extension needs libcouchbase.dll

### ISSUE THREAD

**Issue by shivammathur** [mlocati/powershell-phpmanager#58]
@mlocati Similar to #55 `couchbase` extension needs `libcouchbase.dll` to install correctly. So it should be extracted from the zip archive to the directory in -Path parameter or the default PHP directory.

**Comment by mlocati** [comment]
@shivammathur I just published a new version with a fix for this.

**Comment by shivammathur** [comment]
@mlocati Thanks for the quick fix.
