### ISSUE TITLE
vcredist not installing with `InstallVC` switch

### ISSUE THREAD

**Issue by shivammathur** [mlocati/powershell-phpmanager#74]
Recent changes in [`aaronparker/VcRedist`](https://github.com/aaronparker/VcRedist) module seems to have broken the support to install `vcredist` using `InstallVC` switch.

Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/672272931/workflow

**Comment by mlocati** [comment]
I don't understand which change in vcredist broke phpmanager.
I've asked in the vcredist project: see https://github.com/aaronparker/VcRedist/issues/77

**Comment by shivammathur** [comment]
Fixed in https://github.com/aaronparker/VcRedist/pull/78
