### ISSUE TITLE
Imagick extension missing DLL

### ISSUE THREAD

**Issue by kranack** [mlocati/powershell-phpmanager#84]
**Environment**
Windows 2016 Server
PHP 7.3.25
PHPManager 1.25.2

**Issue Description**
I installed PHP on a fresh new Windows 2016 Server with the latest version of PHPManager but the installation of the imagick extension seemed to not work as intended on some extensions. I realized at some point that one DLL is missing in the PHP install folder, compared to the ImageMagick library folder, the _FILTER_analyze_.dll_ file.
I checked the code in [Install-ImagickPrerequisite.ps1](https://github.com/mlocati/powershell-phpmanager/blob/master/PhpManager/private/Install-ImagickPrerequisite.ps1) and wonder why this file is not copied as well as the CORE_RL_* and the IM_MOD_RL_* DLLs. Is there a reason for not getting this file automatically ?

**Comment by mlocati** [comment]
Which PHP version are you using?

PS: The latest version of PHPManager is 1.25.3 which includes #83

**Comment by mlocati** [comment]
BTW: https://github.com/mlocati/powershell-phpmanager/pull/85

**Comment by kranack** [comment]
I assume you found the PHP version in my issue 😄 
Thanks for you quick response and your PR, do you need me to check your branch / test it on my environment ?

**Comment by mlocati** [comment]
> I assume you found the PHP version in my issue 😄

Yep, sorry

>  Thanks for you quick response and your PR, do you need me to check your branch / test it on my environment ?

No needs to do that, thanks! I'll publish a new release shortly

**Comment by kranack** [comment]
Great, thanks again for you work 👍🏻

**Comment by mlocati** [comment]
> I'll publish a new release shortly

Done: version 1.25.4 should fix the issue
