### ISSUE TITLE
Adjust PHP version regex for PHP 8.1 snap builds

### ISSUE THREAD

**Issue by shivammathur** [mlocati/powershell-phpmanager#87]
PHP 8.1 in the `PHP-8.1` branch has the version `8.1.0RC1-dev`. 
Ref:
- https://github.com/php/php-src/commit/d6d6491153c5b159a6cb0c597785e201f402344e
- https://chat.stackoverflow.com/transcript/message/52943398#52943398

This is unlike PHP 8.0 RCs where the version on the branch was `8.0.0-dev`.
So this change in 8.1 breaks the regex for checking PHP version as it parses `-dev` and `-RC\d`, but not `-RC\d-dev`.

https://github.com/mlocati/powershell-phpmanager/blob/341e3242772cc65b6de39c5458c0412f14ac67ef/PhpManager/private/PhpVersion.ps1#L310

Failure log for `Get-Php`: https://github.com/shivammathur/test-setup-php/runs/3492819490?check_suite_focus=true#step:3:11

**Comment by shivammathur** [comment]
@mlocati 
After the fix, it does not break, but there is a minor issue - the version in `Get-Php` is `8.1.0rc2` with UnstabilityLevel RC. Shouldn't it be `8.1.0rc2-dev` with UnstabilityLevel snapshot?

**Comment by driesvints** [comment]
Seems like none PHP 8.1 tests on windows are also failing now: https://github.com/Krisell/framework/runs/3495992100#step:4:14

**Comment by mlocati** [comment]
> After the fix, it does not break, but there is a minor issue - the version in `Get-Php` is `8.1.0rc2` with UnstabilityLevel RC. Shouldn't it be `8.1.0rc2-dev` with UnstabilityLevel snapshot?

Well, if it's a release candidate, it's not a snapshot. Am I missing something?

**Comment by shivammathur** [comment]
It is a nightly snapshot build from the PHP-8.1 branch, not the tagged rc.
https://github.com/shivammathur/php-builder-windows/releases/tag/php8.1

**Comment by mlocati** [comment]
It seems so strange to me to define a "release candidate" as a "snapshot"...
Why do we have `php-8.1.0RC2-dev` instead of `php-8.1.0-dev` (or `php-8.1.0-snapshot`)?

**Comment by shivammathur** [comment]
Yes, the change seems arbitrary to me also. It should be `php-8.1.0-dev` in the source.

**Comment by shivammathur** [comment]
@driesvints Please try restarting the workflow, 7.4 should not fail.

**Comment by driesvints** [comment]
@shivammathur yeah, it seems it was a temp hiccup, sorry about that!

**Comment by mlocati** [comment]
Here's a better fix: https://github.com/mlocati/powershell-phpmanager/pull/89

**Comment by shivammathur** [comment]
@mlocati Great, I prefer this as `dev` in the version should mean snapshot.
